[package]
name = "blog"
version = "0.1.0"
authors = ["Cody Casterline <cody.casterline@gmail.com>"]
edition = "2018"

[dependencies]
# Web:
actix-web = "1"
actix-web-codegen = "*"

# Error handling:
failure = "*"

# CLI: 
structopt = "*"
webbrowser = "*"

multihash = "*"
rust-base58 = "*"
bs58 = { version = "*", features = ["check"] }

# crypto:
rust_sodium = "0.10.2"
rust_sodium-sys = "*"

# Markdown:
pulldown-cmark = "*"

# Allow embedding local files. 
rust-embed = { version = "*" }
# ... and serving those files w/ the right mime types.
mime_guess = "2"

# (De)serialization for signed blobs:
serde = "*"
serde_derive = "*"
serde_cbor = "0.10"

[dependencies.rusqlite]
version = "*"
features = [
    # Use a bundled, statically-linked version of sqlite. (Simplifies building on Windows)
    "bundled"
]


[dependencies.askama]
version = "*"
# See: https://github.com/djc/askama/issues/246
# features = ["with-actix-web"]

