[package]
name = "blog"
version = "0.1.0"
authors = ["Cody Casterline <cody.casterline@gmail.com>"]
edition = "2018"

[dependencies]
# Web:
actix-web = "3"
actix-web-codegen = "*"
# required for reading Actix Payloads:
futures = "*"
futures-core = "*"
futures-util = "*"

# Error handling:
failure = "*"

# CLI: 
structopt = "0.3.17"
webbrowser = "*"

multihash = "*"
rust-base58 = "*"
bs58 = { version = "*", features = ["check"] }

# crypto:
sodiumoxide = "*"

# Markdown:
pulldown-cmark = "*"

# Allow embedding local files. 
rust-embed = { version = "*" }
# ... and serving those files w/ the right mime types.
mime_guess = "2"



# Used to make Traits that have async functions which can be used as response
# objects with actix-web
async-trait = "*"

protobuf = "2"
time = "0.2"


[dependencies.rusqlite]
version = "0.24"
features = [
    # Use a bundled, statically-linked version of sqlite. (Simplifies building on Windows)
    "bundled"
]


[dependencies.askama]
version = "0.10"
# See: https://github.com/djc/askama/issues/246
# features = ["with-actix-web"]

[build-dependencies]
# Generate rust from .proto files.
protoc-rust = "2"