[package]
name = "blog"
version = "0.1.0"
authors = ["Cody Casterline <cody.casterline@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1"
actix-web-codegen = "*"
sqlite = "*"
structopt = "*"
webbrowser = "*"
failure = "*"
serde = "*"

[dependencies.askama]
version = "*"
# See: https://github.com/djc/askama/issues/246
# features = ["with-actix-web"]

