[package]
name = "blog"
version = "0.1.0"
authors = ["Cody Casterline <cody.casterline@gmail.com>"]
edition = "2018"

[dependencies]
# Web:
actix-web = "1"
actix-web-codegen = "*"

# DB:
sqlite = "*"

# Error handling:
failure = "*"

# CLI: 
structopt = "*"
webbrowser = "*"

multihash = "*"
rust-base58 = "*"

# crypto:
rust_sodium = "*"

# Markdown:
pulldown-cmark = "*"

# (De)serialization for signed blobs:
serde = "*"
serde_derive = "*"
serde_cbor = "0.10"


[dependencies.in-memory-session]
path = "crates/in-memory-session"


[workspace]
members = [
    ".",
    "crates/in-memory-session",
]

[dependencies.askama]
version = "*"
# See: https://github.com/djc/askama/issues/246
# features = ["with-actix-web"]

