[package]
name = "feoblog"
version = "0.3.0"
authors = ["Cody Casterline <cody.casterline@gmail.com>"]
edition = "2018"

[dependencies]
# Web:
actix-web = "3"
actix-web-codegen = "*"
# required for reading Actix Payloads:
futures = "*"

# Error handling:
anyhow = "*"

# CLI: 
structopt = "0.3.17"
webbrowser = "*"

multihash = "*"
rust-base58 = "*"
bs58 = { version = "*", features = ["check"] }

# crypto:
sodiumoxide = "*"

# Markdown:
# Comrak is safe by default:
comrak = "*"

# Allow embedding local files. 
rust-embed = { version = "*" }
# ... and serving those files w/ the right mime types.
mime_guess = "2"



# Used to make Traits that have async functions which can be used as response
# objects with actix-web
async-trait = "*"

# Required fix for soft_unstable rustfmt::skip (as of Rust 1.52).
# See: https://github.com/stepancheg/rust-protobuf/issues/551
protobuf = "^2.22.1"
time = "0.2"

# Used to deserialize strings in URL paths.
serde = "*"

# connection pooling for rusqlite:
r2d2 = "*"
r2d2_sqlite = "*"

log = "*"
env_logger = "*"
logging_timer = "*"

askama_actix = "*"

# To work around https://github.com/actix/actix-web/issues/1913
socket2 = "*"

# A nice library for getting blocking I/O out of the main thread(s)
blocking = "*"

tempfile = "*"

[dependencies.rusqlite]
# TODO: Switch to sqlx for async sql support?
version = "0.24"
features = [
    # Use a bundled, statically-linked version of sqlite. (Simplifies building on Windows)
    "bundled",
    # Enable extra BLOB APIs for streaming large BLOBs:
    "blob",
]


[dependencies.askama]
version = "0.10"
features = ["with-actix-web"]

[build-dependencies]
# Generate rust from .proto files.
protoc-rust = "2"