# I don't see a way to reference jobs from other workflow files, so this is
# mostly a copy of build.yml, with extra steps to publish the results to a release tag.
name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Build
        uses: ./.github/workflows/build.yml

      - name: Download build artifacts
        id: download
        uses: actions/download-artifact@v2
        with:
          path: ./artifacts
      
      - name: Create MacOS artifact
        working-directory: ${{ steps.download.outputs.download-path}}/FeoBlog-macos-latest
        run: zip -9 release.zip feoblog

      - name: Create Linux artifact
        working-directory: ${{ steps.download.outputs.download-path}}/FeoBlog-ubuntu-latest
        run: zip -9 release.zip feoblog

      - name: Create Windows artifact
        working-directory: ${{ steps.download.outputs.download-path}}/FeoBlog-windows-latest
        run: zip -9 release.zip feoblog.exe

      # github.ref gives us something like refs/tags/v1.2.3, but we just want v1.2.3
      - name: Get tag name
        id: tag-name
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            return "${{ github.ref }}".replace("refs/tags/", "")

      - name: Create the release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.tag-name.outputs.result }}
          prerelease: contains(github.ref, '-rc')
          body: |
            See [CHANGELOG.md] for release notes.
            
            [CHANGELOG.md]: https://github.com/NfNitLoop/feoblog/blob/${{ steps.tag-name.outputs.result }}/CHANGELOG.md
          
      - name: Attach MacOS Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.download.outputs.download-path}}/FeoBlog-macos-latest/release.zip
          asset_name: feoblog-macos-${{ steps.tag-name.outputs.result }}.zip
          asset_content_type: application/zip

      - name: Attach Linux (Ubuntu) Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.download.outputs.download-path}}/FeoBlog-ubuntu-latest/release.zip
          asset_name: feoblog-linux-${{ steps.tag-name.outputs.result }}.zip
          asset_content_type: application/zip
      
      - name: Attach Windows Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.download.outputs.download-path}}/FeoBlog-windows-latest/release.zip
          asset_name: feoblog-windows-${{ steps.tag-name.outputs.result }}.zip
          asset_content_type: application/zip

